# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/PyCQA/pylint
    rev: v2.8.3
    hooks:
    -   id: pylint
        args:
          - "tfx_addons"
-   repo:  https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
    -   id: yapf 
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest tfx_addons
        language: system
        pass_filenames: false
        always_run: true
