name: TFX Addons package CI

on:
  push:
    paths:
      - 'tfx_addons/**'
      - '.github/ci/**'
      - '.github/workflows/ci.yml'
      - 'setup.py'
      - 'pyproject.toml'
    branches:
      - main
      - r*
  pull_request:
    paths:
      - 'tfx_addons/**'
      - '.github/ci/**'
      - '.github/workflows/ci.yml'
      - 'setup.py'
      - 'pyproject.toml'
    branches:
      - main
      - r*

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      # Test for several versions of TFX in parallel
      matrix:
        tfxversion: ["~=1.0.0 tensorflow~=2.5.0", "~=1.0.0 tensorflow~=2.5.0"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding setup.py + TFX version 
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}-${{ matrix.tfxversion }}
        restore-keys: |
          ${{ runner.os }}-pip--${{ hashFiles('setup.py') }}
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -e ".[all, test]" tfx${{ matrix.tfxversion }}
    - name: Run tests
      run: pytest tfx_addons
  
