name: GitHub CI

on:
  push:
    branches:
      - main
      - r*
  pull_request:
    branches:
      - main
      - r*

jobs:
  build_tfx_addons:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -e .[all]
    - uses: pre-commit/action@v2.0.3
