name: TFX Addons nightly CI

on:
  push:
    paths-ignore:
      - 'proposals/**'
      - 'examples/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'proposals/**'
      - 'examples/**'
    branches:
      - main


jobs:
  pytest-nighlty-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding setup.py + TFX version 
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip--${{ hashFiles('setup.py') }}
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install --extra-index-url https://pypi-nightly.tensorflow.org/simple/ --pre -e ".[all, test]" tfx
    - name: Run tests
      run: pytest
  
